cpu:
  dynamic_scheduling: 0 # 0,1
  # 1->dynamic scheduling (Tomasulo's algorithm)
  alu_reservation_stations: 5
  ls_reservation_stations: 5
  load_buffers: 10
  store_buffers: 10
  rob_size: 10 # Maximum Value = 2^8-1 = 255
  # 0->static scheduling, only corresponding parameters will be used
  pipeline_stages: 5 # 3,4,5,7

memory:
  l1_icache_size: 128 # in KiB
  l1_dcache_size: 128 # in KiB
  l2_cache_size: 1024 # in KiB
  dram_size: 1024 # in MiB (Max 4GiB = 4096MiB)
  dram_start_address: 0x00000000
  instr_start_address: 0x08000000

enable_stats:
  cache_misses: 1 # 0,1
  branch_mispredictions: 1 # 0,1
  memory_heatmap: 0 # 0,1
  register_heatmap: 0 # 0,1

logs:
  verbosity_level: 3 # 0->INFO, 1->DEBUG, 2->WARN, 3->ERROR
