#ifndef CONFIG_DEFINES_H
#define CONFIG_DEFINES_H

#define DYNAMIC_SCHEDULING 0
#define ALU_RESERVATION_STATIONS 5
#define LS_RESERVATION_STATIONS 5
#define LOAD_BUFFERS 10
#define STORE_BUFFERS 10
#define ROB_SIZE 10
#define PIPELINE_STAGES 5
#define L1_ICACHE_SIZE 128
#define L1_DCACHE_SIZE 128
#define L2_CACHE_SIZE 1024
#define DRAM_SIZE 1024
#define DRAM_START_ADDRESS 0x00000000
#define INSTR_START_ADDRESS 0x08000000
#define CACHE_MISSES 1
#define BRANCH_MISPREDICTIONS 1
#define MEMORY_HEATMAP 0
#define REGISTER_HEATMAP 0
#define VERBOSITY_LEVEL 3

#endif // !CONFIG_DEFINES_H
